### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by DaveCalaway** [Autodrop3d/raspi-scripts#1]
Raspbian: June 2019 - Release date:2019-06-20 

Hello,
i'm using the last version of raspbian on my RPi zero W.
I haven't install any dependency, like dnsmasq hostapd.

When the RPi start, Client mode, it give me this screen after "ifconfig".
Why i read ethernet over wlan0?
![Client](https://user-images.githubusercontent.com/10884164/60835334-20a6ae80-a1c3-11e9-8810-13cbf6c494e5.jpg)

If i decide to swith to AP, this is the result after "ifconfig".
It's a good ip, static, but again ethernet over ap0.
![AP](https://user-images.githubusercontent.com/10884164/60835050-7fb7f380-a1c2-11e9-840a-9d016175d364.jpg)

Do i miss something?

**Comment by ghost** [comment]
It seems as though when you ran the setup script, you entered either an incorrect SSID and/or password which is why you didn't get an IP. Run it again with the right information and it should be ok.
